# Generated by Django 4.2 on 2023-06-26 07:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tehsil', models.CharField(choices=[('Badnagar', 'Badnagar'), ('Ghatiya', 'Ghatiya'), ('Jharda', 'Jharda'), ('Khachrod', 'Khachrod'), ('Mahidpur', 'Mahidpur'), ('Makdone', 'Makdone'), ('Nagda', 'Nagda'), ('Tarana', 'Tarana')], max_length=50)),
                ('Police_station', models.CharField(max_length=50)),
                ('Criminal_address', models.CharField(blank=True, max_length=50)),
                ('Criminal_name', models.CharField(blank=True, max_length=100)),
                ('Criminal_mobile_No', models.CharField(blank=True, max_length=50)),
                ('anonymous', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=20)),
                ('Permanent_address', models.CharField(max_length=100)),
                ('Mobile_NO', models.CharField(max_length=10)),
                ('place_of_crime', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.date(2023, 6, 26))),
                ('Time', models.TimeField(default=datetime.datetime(2023, 6, 26, 7, 58, 11, 160513, tzinfo=datetime.timezone.utc))),
                ('TitleOfCrime', models.CharField(max_length=80)),
                ('content', models.TextField(max_length=255)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 7, 58, 11, 160513, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
