# Generated by Django 4.2 on 2023-06-26 08:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crime_Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 26, 8, 20, 2, 182878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 8, 20, 2, 182878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='tesil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tehsil', models.CharField(choices=[('Badnagar', 'Badnagar'), ('Ghatiya', 'Ghatiya'), ('Jharda', 'Jharda'), ('Khachrod', 'Khachrod'), ('Mahidpur', 'Mahidpur'), ('Makdone', 'Makdone'), ('Nagda', 'Nagda'), ('Tarana', 'Tarana')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
