# Generated by Django 4.2 on 2023-07-15 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime_Report', '0002_alter_fir_time_alter_fir_date_posted_tesil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 7, 16)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 15, 18, 32, 32, 75416, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 18, 32, 32, 75416, tzinfo=datetime.timezone.utc)),
        ),
    ]
